# Lua 5.1 Makefile for ELKS, compiled using OpenWatcom C
# make -f Makefile.elks

ifndef TOPDIR
$(error ELKS TOPDIR is not defined)
endif

ifndef WATCOM
$(error OpenWatcom WATCOM is not defined)
endif

CC = owcc
LD = owcc

CLBASE = -mcmodel=l
CLBASE += -bnone -march=i86 -std=c99
CLBASE += -fno-stack-check -fnostdlib -fsigned-char
CLBASE += -Wc,-fpc -Wc,-zev -Wc,-zls -Wc,-x -Wc,-wcd=303

WARNINGS = -Wall -Wextra

INCLUDES = -I$(TOPDIR)/libc/include -I$(TOPDIR)/elks/include
INCLUDES += -I$(TOPDIR)/libc/include/watcom

DEFINES = -D__ELKS__ -DLUA_ANSI

# ------------------------------------------------------------
# Optional Nano-X client backend. Switches graphics from VGA to Nano-X when
# USE_NANOX_BACKEND=1.
# NANOX_DIR must point to the Nano-X source directory containing:
# include/ nanox/ drivers/
# Example:
#   make -f Makefile.elks USE_NANOX_BACKEND=1 NANOX_DIR=/root/microwindows/src
# ------------------------------------------------------------
USE_NANOX_BACKEND ?= 0
NANOX_DIR ?= YOUR_MICROWINDOWS_DIRECTORY/src

ifeq ($(USE_NANOX_BACKEND),1)
DEFINES += -DUSE_NANOX_BACKEND
DEFINES += -DELKS=1 -DUNIX=1 -DNONETWORK=0
DEFINES += -DMWPIXEL_FORMAT=MWPF_PALETTE
DEFINES += -DSCREEN_PIXTYPE=MWPF_PALETTE

INCLUDES += -I$(NANOX_DIR)/include
INCLUDES += -I$(NANOX_DIR)/nanox
INCLUDES += -I$(NANOX_DIR)/drivers

NANOX_CLIENT_OBJS = nx_client.obj nx_nxproto.obj nx_nxutil.obj nx_osdep.obj
endif

CFLAGS = -Os $(CLBASE) $(WARNINGS) $(INCLUDES) $(DEFINES) $(LOCALFLAGS)

LDBASE = -bos2 -s
LDBASE += -Wl,option -Wl,dosseg
LDBASE += -Wl,option -Wl,start=_start
LDBASE += -Wl,option -Wl,nodefaultlibs
LDBASE += -Wl,option -Wl,stack=0x2000
LDBASE += -Wl,option -Wl,heapsize=512

LDFLAGS = $(LDBASE)
LDLIBS = -Wl,library -Wl,$(TOPDIR)/libc/libcl.lib

OBJS = $(SRCS:.c=.obj) $(NANOX_CLIENT_OBJS)

%.obj: %.c
	$(CC) -c $(CFLAGS) -o $*.obj $<

BINDIR = ../elks-bin
LOCALFLAGS = -DNDEBUG
PROG = lua luac

SRCS = mem.c lmathlib.c lapi.c lcode.c ldebug.c ldo.c ldump.c lfunc.c lgc.c llex.c lmem.c \
	lobject.c lopcodes.c lparser.c lstate.c lstring.c ltable.c ltm.c \
	lundump.c lvm.c lzio.c lauxlib.c lbaselib.c ldblib.c liolib.c loslib.c ltablib.c \
	lstrlib.c loadlib.c linit.c

all: $(PROG)

elks: all

lua: $(OBJS) lua.obj
	$(LD) $(LDFLAGS) -o $@ $(OBJS) lua.obj $(LDLIBS)

luac: $(OBJS) luac.obj print.obj
	$(LD) $(LDFLAGS) -o $@ $(OBJS) luac.obj print.obj $(LDLIBS)

lua.obj: lua.c
	$(CC) -c $(CFLAGS) -o lua.obj $<

luac.obj: luac.c
	$(CC) -c $(CFLAGS) -o luac.obj $<

print.obj: print.c
	$(CC) -c $(CFLAGS) -o print.obj $<

nx_client.obj: $(NANOX_DIR)/nanox/client.c
	$(CC) -c $(CFLAGS) -o $@ $<

nx_nxproto.obj: $(NANOX_DIR)/nanox/nxproto.c
	$(CC) -c $(CFLAGS) -o $@ $<

nx_nxutil.obj: $(NANOX_DIR)/nanox/nxutil.c
	$(CC) -c $(CFLAGS) -o $@ $<

nx_osdep.obj: $(NANOX_DIR)/drivers/osdep.c
	$(CC) -c $(CFLAGS) -o $@ $<

clean:
	rm -f $(PROG) *.obj tmp.h
